from dataclasses import dataclass
from statistics import fmean

from ac_race_engineer.telemetry.assetto_corsa.trace import (
    DrivingTraceSample,
)
from ac_race_engineer.telemetry.assetto_corsa.trace_corner_entry import (
    CornerEntry,
)


@dataclass(frozen=True)
class CornerExit:
    exit_number: int
    source_entry_number: int

    apex_progress: float
    exit_progress: float

    apex_elapsed_seconds: float
    exit_elapsed_seconds: float
    duration_seconds: float

    throttle_application_progress: float
    throttle_application_elapsed_seconds: float
    time_to_throttle_seconds: float

    apex_speed_kmh: float
    exit_speed_kmh: float
    speed_gain_kmh: float

    throttle_at_apex: float
    throttle_at_exit: float

    steering_at_apex_deg: float
    steering_at_exit_deg: float

    maximum_abs_steering_deg: float
    average_abs_steering_deg: float
    steering_unwind_deg: float

    sample_count: int

    @property
    def progress_span(
        self,
    ) -> float:
        return (
            self.exit_progress
            - self.apex_progress
        )


class AssettoCorsaCornerExitService:
    """
    Detect corner-exit phases after a previously detected apex.

    The exit starts at the apex proxy generated by CornerEntry.

    A valid corner exit requires:

    - meaningful throttle application,
    - steering unwinding,
    - sufficient throttle at the exit,
    - steering below the configured exit threshold.

    This service describes telemetry only.
    It does not diagnose driver behaviour.
    """

    def __init__(
        self,
        *,
        throttle_application_threshold: float = 0.20,
        exit_throttle_threshold: float = 0.70,
        exit_steering_threshold_deg: float = 8.0,
        lookahead_progress: float = 0.12,
        minimum_samples: int = 2,
    ) -> None:
        if not (
            0.0
            < throttle_application_threshold
            <= 1.0
        ):
            raise ValueError(
                "throttle_application_threshold must "
                "be greater than 0 and at most 1"
            )

        if not (
            0.0
            < exit_throttle_threshold
            <= 1.0
        ):
            raise ValueError(
                "exit_throttle_threshold must "
                "be greater than 0 and at most 1"
            )

        if exit_steering_threshold_deg < 0.0:
            raise ValueError(
                "exit_steering_threshold_deg "
                "cannot be negative"
            )

        if not (
            0.0
            < lookahead_progress
            <= 1.0
        ):
            raise ValueError(
                "lookahead_progress must be "
                "greater than 0 and at most 1"
            )

        if minimum_samples < 2:
            raise ValueError(
                "minimum_samples must be at least 2"
            )

        self.throttle_application_threshold = (
            throttle_application_threshold
        )

        self.exit_throttle_threshold = (
            exit_throttle_threshold
        )

        self.exit_steering_threshold_deg = (
            exit_steering_threshold_deg
        )

        self.lookahead_progress = (
            lookahead_progress
        )

        self.minimum_samples = (
            minimum_samples
        )

    @staticmethod
    def _validate_samples(
        samples: tuple[
            DrivingTraceSample,
            ...,
        ],
    ) -> None:
        previous_progress: float | None = None
        previous_elapsed: float | None = None

        for sample in samples:
            if not (
                0.0
                <= sample.progress
                <= 1.0
            ):
                raise ValueError(
                    "Trace progress must be "
                    "between 0 and 1"
                )

            if sample.elapsed_seconds < 0.0:
                raise ValueError(
                    "Elapsed seconds cannot "
                    "be negative"
                )

            if not (
                0.0
                <= sample.throttle
                <= 1.0
            ):
                raise ValueError(
                    "Throttle input must be "
                    "between 0 and 1"
                )

            if (
                previous_progress is not None
                and sample.progress
                < previous_progress
            ):
                raise ValueError(
                    "Trace progress must be "
                    "monotonically increasing"
                )

            if (
                previous_elapsed is not None
                and sample.elapsed_seconds
                < previous_elapsed
            ):
                raise ValueError(
                    "Trace elapsed time must be "
                    "monotonically increasing"
                )

            previous_progress = (
                sample.progress
            )

            previous_elapsed = (
                sample.elapsed_seconds
            )

    def _samples_for_entry(
        self,
        *,
        samples: tuple[
            DrivingTraceSample,
            ...,
        ],
        entry: CornerEntry,
    ) -> tuple[
        DrivingTraceSample,
        ...,
    ]:
        maximum_progress = min(
            1.0,
            (
                entry.apex_progress
                + self.lookahead_progress
            ),
        )

        return tuple(
            sample
            for sample in samples
            if (
                entry.apex_progress
                <= sample.progress
                <= maximum_progress
            )
        )

    def _find_throttle_application_index(
        self,
        samples: tuple[
            DrivingTraceSample,
            ...,
        ],
    ) -> int | None:
        for index, sample in enumerate(
            samples
        ):
            if (
                sample.throttle
                >= self.throttle_application_threshold
            ):
                return index

        return None

    def _find_exit_index(
        self,
        samples: tuple[
            DrivingTraceSample,
            ...,
        ],
        *,
        start_index: int,
    ) -> int | None:
        for index in range(
            start_index,
            len(samples),
        ):
            sample = samples[
                index
            ]

            enough_throttle = (
                sample.throttle
                >= self.exit_throttle_threshold
            )

            steering_unwound = (
                abs(
                    sample.steering_angle_deg
                )
                <= self.exit_steering_threshold_deg
            )

            if (
                enough_throttle
                and steering_unwound
            ):
                return index

        return None

    def _build_exit(
        self,
        *,
        exit_number: int,
        entry: CornerEntry,
        samples: tuple[
            DrivingTraceSample,
            ...,
        ],
    ) -> CornerExit | None:
        throttle_index = (
            self._find_throttle_application_index(
                samples
            )
        )

        if throttle_index is None:
            return None

        exit_index = (
            self._find_exit_index(
                samples,
                start_index=throttle_index,
            )
        )

        if exit_index is None:
            return None

        analysis_samples = (
            samples[
                : exit_index + 1
            ]
        )

        if (
            len(analysis_samples)
            < self.minimum_samples
        ):
            return None

        apex = (
            analysis_samples[0]
        )

        throttle_application = (
            samples[
                throttle_index
            ]
        )

        exit_sample = (
            samples[
                exit_index
            ]
        )

        steering_values = [
            abs(
                sample.steering_angle_deg
            )
            for sample in analysis_samples
        ]

        duration_seconds = max(
            0.0,
            (
                exit_sample.elapsed_seconds
                - apex.elapsed_seconds
            ),
        )

        time_to_throttle = max(
            0.0,
            (
                throttle_application
                .elapsed_seconds
                - apex.elapsed_seconds
            ),
        )

        speed_gain = (
            exit_sample.speed_kmh
            - apex.speed_kmh
        )

        steering_unwind = max(
            0.0,
            (
                abs(
                    apex.steering_angle_deg
                )
                - abs(
                    exit_sample
                    .steering_angle_deg
                )
            ),
        )

        return CornerExit(
            exit_number=exit_number,
            source_entry_number=(
                entry.entry_number
            ),
            apex_progress=(
                apex.progress
            ),
            exit_progress=(
                exit_sample.progress
            ),
            apex_elapsed_seconds=(
                apex.elapsed_seconds
            ),
            exit_elapsed_seconds=(
                exit_sample.elapsed_seconds
            ),
            duration_seconds=(
                duration_seconds
            ),
            throttle_application_progress=(
                throttle_application.progress
            ),
            throttle_application_elapsed_seconds=(
                throttle_application
                .elapsed_seconds
            ),
            time_to_throttle_seconds=(
                time_to_throttle
            ),
            apex_speed_kmh=(
                apex.speed_kmh
            ),
            exit_speed_kmh=(
                exit_sample.speed_kmh
            ),
            speed_gain_kmh=(
                speed_gain
            ),
            throttle_at_apex=(
                apex.throttle
            ),
            throttle_at_exit=(
                exit_sample.throttle
            ),
            steering_at_apex_deg=(
                apex.steering_angle_deg
            ),
            steering_at_exit_deg=(
                exit_sample
                .steering_angle_deg
            ),
            maximum_abs_steering_deg=max(
                steering_values
            ),
            average_abs_steering_deg=fmean(
                steering_values
            ),
            steering_unwind_deg=(
                steering_unwind
            ),
            sample_count=len(
                analysis_samples
            ),
        )

    def analyze(
        self,
        *,
        samples: tuple[
            DrivingTraceSample,
            ...,
        ],
        entries: tuple[
            CornerEntry,
            ...,
        ],
    ) -> tuple[
        CornerExit,
        ...,
    ]:
        if not samples:
            return ()

        if not entries:
            return ()

        self._validate_samples(
            samples
        )

        exits: list[
            CornerExit
        ] = []

        for entry in entries:
            entry_samples = (
                self._samples_for_entry(
                    samples=samples,
                    entry=entry,
                )
            )

            if (
                len(entry_samples)
                < self.minimum_samples
            ):
                continue

            corner_exit = (
                self._build_exit(
                    exit_number=(
                        len(exits) + 1
                    ),
                    entry=entry,
                    samples=entry_samples,
                )
            )

            if corner_exit is None:
                continue

            exits.append(
                corner_exit
            )

        return tuple(
            exits
        )