"""add assetto corsa laps and sectors

Revision ID: 44e11f6dc9e1
Revises: 624acdf2b31d
Create Date: 2026-09-28 18:46:38.909782

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '44e11f6dc9e1'
down_revision: str | Sequence[str] | None = '624acdf2b31d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_ms', sa.Integer(), nullable=False),
    sa.Column('best_lap_time_ms', sa.Integer(), nullable=False),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_in_pit', sa.Boolean(), nullable=False),
    sa.Column('is_in_pit_lane', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'lap_number', name='uq_laps_session_lap_number')
    )
    op.create_index(op.f('ix_laps_session_id'), 'laps', ['session_id'], unique=False)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('sector_index', sa.Integer(), nullable=False),
    sa.Column('sector_number', sa.Integer(), nullable=False),
    sa.Column('sector_time_ms', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_in_pit', sa.Boolean(), nullable=False),
    sa.Column('is_in_pit_lane', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'lap_number', 'sector_number', name='uq_sectors_session_lap_sector')
    )
    op.create_index(op.f('ix_sectors_lap_number'), 'sectors', ['lap_number'], unique=False)
    op.create_index(op.f('ix_sectors_session_id'), 'sectors', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sectors_session_id'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_lap_number'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_laps_session_id'), table_name='laps')
    op.drop_table('laps')
    # ### end Alembic commands ###
