"""initial relational schema

Revision ID: 624acdf2b31d
Revises: 
Create Date: 2026-09-24 16:25:04.702014

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '624acdf2b31d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('drivetrain', sa.String(length=32), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_car_key'), 'cars', ['car_key'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('layout', sa.String(length=120), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_track_key'), 'tracks', ['track_key'], unique=True)
    op.create_table('setups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setup_key', sa.String(length=120), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setups_car_id'), 'setups', ['car_id'], unique=False)
    op.create_index(op.f('ix_setups_setup_key'), 'setups', ['setup_key'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('baseline_setup_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_setup_id'], ['setups.id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_car_id'), 'experiments', ['car_id'], unique=False)
    op.create_index(op.f('ix_experiments_track_id'), 'experiments', ['track_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('raw_path', sa.String(length=500), nullable=True),
    sa.Column('bronze_path', sa.String(length=500), nullable=True),
    sa.Column('silver_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_car_id'), 'sessions', ['car_id'], unique=False)
    op.create_index(op.f('ix_sessions_setup_id'), 'sessions', ['setup_id'], unique=False)
    op.create_index(op.f('ix_sessions_track_id'), 'sessions', ['track_id'], unique=False)
    op.create_table('gold_session_metrics',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('ml_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=True),
    sa.Column('model_type', sa.String(length=120), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_runs_experiment_id'), 'ml_runs', ['experiment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_runs_experiment_id'), table_name='ml_runs')
    op.drop_table('ml_runs')
    op.drop_table('gold_session_metrics')
    op.drop_index(op.f('ix_sessions_track_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_setup_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_car_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_experiments_track_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_car_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_setups_setup_key'), table_name='setups')
    op.drop_index(op.f('ix_setups_car_id'), table_name='setups')
    op.drop_table('setups')
    op.drop_index(op.f('ix_tracks_track_key'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_cars_car_key'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
