"""add Assetto Corsa lap traces

Revision ID: b2fa323089d0
Revises: 44e11f6dc9e1
Create Date: 2026-09-29 18:40:37.842178

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2fa323089d0'
down_revision: str | Sequence[str] | None = '44e11f6dc9e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lap_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_ms', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('progress_start', sa.Float(), nullable=False),
    sa.Column('progress_end', sa.Float(), nullable=False),
    sa.Column('parquet_path', sa.String(length=500), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'lap_number', name='uq_lap_traces_session_lap_number')
    )
    op.create_index(op.f('ix_lap_traces_lap_number'), 'lap_traces', ['lap_number'], unique=False)
    op.create_index(op.f('ix_lap_traces_session_id'), 'lap_traces', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lap_traces_session_id'), table_name='lap_traces')
    op.drop_index(op.f('ix_lap_traces_lap_number'), table_name='lap_traces')
    op.drop_table('lap_traces')
    # ### end Alembic commands ###
